version: "3"
services:
  freeipa:
    image: docker.io/freeipa/freeipa-server:rocky-9
    hostname: ec2-65-0-150-75.ap-south-1.compute.amazonaws.com
    ports:
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "80:80"
      - "443:443"
    volumes:
      - freeipa-data:/data
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - /run
      - /tmp
      
    extra_hosts:
    - "ec2-65-0-150-75.ap-south-1.compute.amazonaws.com:65.0.150.75"

volumes:
  freeipa-data:
