version: "3"
services:
  freeipa:
    image: docker.io/freeipa/freeipa-server:rocky-9
    hostname: ipa.packops.local
    network_mode: "host"
    privileged: true
    environment:
      - DS_PASSWORD=Admin@123
      - ADMIN_PASSWORD=Admin@123
    volumes:
      - freeipa-data:/data
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - /run
      - /tmp
    command:
      - -U
      - --realm=PACKOPS.LOCAL
      - --domain=packops.local
      - --unattended

volumes:
  freeipa-data:
